import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { PaletteInitializer } from "@/components/palette-initializer";
import { PaletteScript } from "@/components/palette-script";
import { DirectionProvider, type DirectionMode } from "@/components/direction-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { TenantProvider } from "@/contexts/TenantContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  interactiveWidget: "resizes-content",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const storedDirection = cookieStore.get("talmudpedia-direction")?.value as DirectionMode | undefined;
  const initialDirection: DirectionMode = storedDirection === "ltr" ? "ltr" : "rtl";

  return (
    <html lang="en" dir={initialDirection} data-direction={initialDirection} suppressHydrationWarning>
      <head>
        <PaletteScript />
      </head>
      <body
        suppressHydrationWarning
        dir={initialDirection}
        data-direction={initialDirection}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <PaletteInitializer />
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}>
            <DirectionProvider initialDirection={initialDirection}>
              <TenantProvider>
                {children}
              </TenantProvider>
            </DirectionProvider>
          </GoogleOAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
