import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { PaletteInitializer } from "@/components/palette-initializer";
import { PaletteScript } from "@/components/palette-script";
import { DirectionProvider } from "@/components/direction-provider";
import { OrganizationProvider } from "@/contexts/OrganizationContext";
import { AuthRefresher } from "@/components/auth-refresher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  interactiveWidget: "resizes-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" data-direction="ltr" suppressHydrationWarning>
      <head>
        <PaletteScript />
      </head>
      <body
        suppressHydrationWarning
        dir="ltr"
        data-direction="ltr"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <PaletteInitializer />
          <DirectionProvider>
            <OrganizationProvider>
              <AuthRefresher />
              {children}
            </OrganizationProvider>
          </DirectionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
