import type { DemoBenchmark, DemoClient, DemoDeal } from "./contracts.js";

export const DEMO_CLIENTS: DemoClient[] = [
  { id: "9192", name: "Astera Manufacturing", sector: "Industrial", baseCurrency: "EUR" },
  { id: "1044", name: "Lumen Retail Group", sector: "Retail", baseCurrency: "USD" },
  { id: "5010", name: "Orchid Foods", sector: "Consumer", baseCurrency: "GBP" },
];

export const DEMO_DEALS: DemoDeal[] = [
  {
    dealId: "200462",
    clientId: "9192",
    bank: "Bank 26",
    currency: "EUR",
    currencyPair: "EUR/ILS",
    executionDate: "2026-02-02",
    notional: 1250000,
    rate: 4.08,
    productFamily: "Spot Hedge",
    timeline: [
      { source: "prico.iskaot", label: "Deal created", eventTime: "2026-02-02T09:15:00Z" },
      { source: "prico.yoman", label: "Execution log recorded", eventTime: "2026-02-02T09:16:00Z" },
      { source: "prico.paku", label: "Exposure rollup matched", eventTime: "2026-02-02T09:19:00Z" },
    ],
    exposureTotal: 1250000,
    sourceTablesUsed: ["prico.iskaot", "prico.bankim", "prico.yoman", "prico.paku"],
  },
  {
    dealId: "200463",
    clientId: "9192",
    bank: "Bank 26",
    currency: "EUR",
    currencyPair: "EUR/ILS",
    executionDate: "2026-02-12",
    notional: 890000,
    rate: 4.06,
    productFamily: "Forward",
    timeline: [
      { source: "prico.iskaot", label: "Deal created", eventTime: "2026-02-12T10:05:00Z" },
      { source: "prico.yoman", label: "Execution log recorded", eventTime: "2026-02-12T10:08:00Z" },
    ],
    exposureTotal: 890000,
    sourceTablesUsed: ["prico.iskaot", "prico.bankim", "prico.yoman"],
  },
  {
    dealId: "200464",
    clientId: "9192",
    bank: "Bank 11",
    currency: "USD",
    currencyPair: "USD/ILS",
    executionDate: "2026-02-20",
    notional: 640000,
    rate: 3.69,
    productFamily: "Forward",
    timeline: [
      { source: "prico.iskaot", label: "Deal created", eventTime: "2026-02-20T08:32:00Z" },
      { source: "prico.ssars", label: "Swap/rollup linked", eventTime: "2026-02-20T08:36:00Z" },
    ],
    exposureTotal: 640000,
    sourceTablesUsed: ["prico.iskaot", "prico.bankim", "prico.ssars"],
  },
  {
    dealId: "200465",
    clientId: "9192",
    bank: "Bank 26",
    currency: "EUR",
    currencyPair: "EUR/ILS",
    executionDate: "2026-02-24",
    notional: 1100000,
    rate: 4.1,
    productFamily: "Spot Hedge",
    timeline: [
      { source: "prico.iskaot", label: "Deal created", eventTime: "2026-02-24T11:41:00Z" },
      { source: "prico.nigrarot_bankaiyot", label: "Bank exposure aggregated", eventTime: "2026-02-24T11:47:00Z" },
    ],
    exposureTotal: 1100000,
    sourceTablesUsed: ["prico.iskaot", "prico.bankim", "prico.nigrarot_bankaiyot"],
  },
  {
    dealId: "100901",
    clientId: "1044",
    bank: "Bank 19",
    currency: "USD",
    currencyPair: "USD/ILS",
    executionDate: "2026-02-10",
    notional: 760000,
    rate: 3.72,
    productFamily: "Forward",
    timeline: [
      { source: "prico.iskaot", label: "Deal created", eventTime: "2026-02-10T12:01:00Z" },
    ],
    exposureTotal: 760000,
    sourceTablesUsed: ["prico.iskaot", "prico.bankim"],
  },
  {
    dealId: "300210",
    clientId: "5010",
    bank: "Bank 31",
    currency: "GBP",
    currencyPair: "GBP/ILS",
    executionDate: "2026-02-05",
    notional: 510000,
    rate: 4.77,
    productFamily: "Forward",
    timeline: [
      { source: "prico.iskaot", label: "Deal created", eventTime: "2026-02-05T07:58:00Z" },
    ],
    exposureTotal: 510000,
    sourceTablesUsed: ["prico.iskaot", "prico.bankim"],
  },
];

export const DEMO_BENCHMARKS: DemoBenchmark[] = [
  { currencyPair: "EUR/ILS", date: "2026-02-02", source: "dbo.shar_yomi", rate: 4.06, confidence: "medium", warnings: ["Benchmark currency mapping inferred from demo pair catalog."] },
  { currencyPair: "EUR/ILS", date: "2026-02-12", source: "dbo.shar_yomi", rate: 4.05, confidence: "medium" },
  { currencyPair: "USD/ILS", date: "2026-02-20", source: "dbo.CurrencyPairsHistory", rate: 3.68, confidence: "high" },
  { currencyPair: "EUR/ILS", date: "2026-02-24", source: "dbo.CurrencyPairsHistory", rate: 4.07, confidence: "medium" },
  { currencyPair: "USD/ILS", date: "2026-02-10", source: "dbo.CurrencyPairsHistory", rate: 3.71, confidence: "high" },
  { currencyPair: "GBP/ILS", date: "2026-02-05", source: "dbo.shar_yomi", rate: 4.8, confidence: "low", warnings: ["GBP benchmark coverage is sparse in the demo dataset."] },
];
