"""add_pipeline_type_to_rag_pipelines

Revision ID: 172b677007a5
Revises: cdfb1a48b29a
Create Date: 2026-02-01 02:06:56.339746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172b677007a5'
down_revision: Union[str, None] = 'cdfb1a48b29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pipelinetype = sa.Enum('INGESTION', 'RETRIEVAL', name='pipelinetype')
    pipelinetype.create(op.get_bind())
    
    op.add_column('executable_pipelines', sa.Column('pipeline_type', pipelinetype, nullable=False, server_default='INGESTION'))
    op.add_column('visual_pipelines', sa.Column('pipeline_type', pipelinetype, nullable=False, server_default='INGESTION'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_pipelines', 'pipeline_type')
    op.drop_column('executable_pipelines', 'pipeline_type')
    
    pipelinetype = sa.Enum('INGESTION', 'RETRIEVAL', name='pipelinetype')
    pipelinetype.drop(op.get_bind())
    # ### end Alembic commands ###
