"""Add chat and message tables

Revision ID: 2891b6fde332
Revises: 104ae692d66d
Create Date: 2026-01-13 16:14:38.741751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2891b6fde332'
down_revision: Union[str, None] = '104ae692d66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_tenant_id'), 'chats', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'AZURE', 'CUSTOM', name='modelprovidertype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=True),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_tenant_id'), 'model_registry', ['tenant_id'], unique=False)
    op.create_table('rag_pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('embedding_model_id', sa.String(), nullable=True),
    sa.Column('vector_db_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_pipelines_slug'), 'rag_pipelines', ['slug'], unique=True)
    op.create_index(op.f('ix_rag_pipelines_tenant_id'), 'rag_pipelines', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_role_tenant_name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('tool_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scope', sa.Enum('GLOBAL', 'TENANT', 'USER', name='tooldefinitionscope'), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_registry_name'), 'tool_registry', ['name'], unique=False)
    op.create_index(op.f('ix_tool_registry_slug'), 'tool_registry', ['slug'], unique=True)
    op.create_index(op.f('ix_tool_registry_tenant_id'), 'tool_registry', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SERVICE', 'AGENT', name='actortype'), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'DELETE', 'EXECUTE', 'ADMIN', name='action'), nullable=False),
    sa.Column('resource_type', sa.Enum('INDEX', 'PIPELINE', 'JOB', 'TENANT', 'ORG_UNIT', 'ROLE', 'MEMBERSHIP', 'AUDIT', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('resource_name', sa.String(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', 'DENIED', name='auditresult'), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_unit_id'), 'audit_logs', ['org_unit_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='ingestionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['rag_pipelines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_pipeline_id'), 'ingestion_jobs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_tenant_id'), 'ingestion_jobs', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result_id', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SERVICE', 'AGENT', name='actortype'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignments_role_id'), 'role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_scope_id'), 'role_assignments', ['scope_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_tenant_id'), 'role_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('INDEX', 'PIPELINE', 'JOB', 'TENANT', 'ORG_UNIT', 'ROLE', 'MEMBERSHIP', 'AUDIT', name='resourcetype'), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'DELETE', 'EXECUTE', 'ADMIN', name='action'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'resource_type', 'action', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('tool_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('artifact_url', sa.String(), nullable=True),
    sa.Column('schema_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_versions_tool_id'), 'tool_versions', ['tool_id'], unique=False)
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_constraint('agent_runs_agent_id_fkey', 'agent_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_runs', 'agents', ['agent_id'], ['id'])
    op.drop_index('ix_agent_traces_span_id', table_name='agent_traces')
    op.drop_constraint('agent_traces_run_id_fkey', 'agent_traces', type_='foreignkey')
    op.create_foreign_key(None, 'agent_traces', 'agent_runs', ['run_id'], ['id'])
    op.drop_constraint('agent_versions_agent_id_fkey', 'agent_versions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_versions', 'agents', ['agent_id'], ['id'])
    op.drop_index('ix_agents_status', table_name='agents')
    op.alter_column('org_units', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('org_units', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.drop_constraint(None, 'agent_versions', type_='foreignkey')
    op.create_foreign_key('agent_versions_agent_id_fkey', 'agent_versions', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'agent_traces', type_='foreignkey')
    op.create_foreign_key('agent_traces_run_id_fkey', 'agent_traces', 'agent_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_agent_traces_span_id', 'agent_traces', ['span_id'], unique=False)
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.create_foreign_key('agent_runs_agent_id_fkey', 'agent_runs', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.drop_index(op.f('ix_tool_versions_tool_id'), table_name='tool_versions')
    op.drop_table('tool_versions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_tenant_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_scope_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_role_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_ingestion_jobs_tenant_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_pipeline_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_unit_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tool_registry_tenant_id'), table_name='tool_registry')
    op.drop_index(op.f('ix_tool_registry_slug'), table_name='tool_registry')
    op.drop_index(op.f('ix_tool_registry_name'), table_name='tool_registry')
    op.drop_table('tool_registry')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rag_pipelines_tenant_id'), table_name='rag_pipelines')
    op.drop_index(op.f('ix_rag_pipelines_slug'), table_name='rag_pipelines')
    op.drop_table('rag_pipelines')
    op.drop_index(op.f('ix_model_registry_tenant_id'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_tenant_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
