"""add checkpoint to agent_runs

Revision ID: 2f4d7ccd1f19
Revises: a9b8c7d6e5f4
Create Date: 2026-01-28 22:54:39.046752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f4d7ccd1f19'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_jobs_pipeline_id', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_tenant_id', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.add_column('agent_runs', sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'checkpoint')
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pipeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='ingestionstatus'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='ingestion_jobs_created_by_fkey'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['rag_pipelines.id'], name='ingestion_jobs_pipeline_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='ingestion_jobs_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingestion_jobs_pkey')
    )
    op.create_index('ix_ingestion_jobs_tenant_id', 'ingestion_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_ingestion_jobs_pipeline_id', 'ingestion_jobs', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###
