"""add_visual_pipeline_executable_pipeline_job_tables

Revision ID: 3d15462ab421
Revises: 4e6b690a38e2
Create Date: 2026-01-18 22:07:02.307377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d15462ab421'
down_revision: Union[str, None] = '4e6b690a38e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_pipelines_org_unit_id'), 'visual_pipelines', ['org_unit_id'], unique=False)
    op.create_index(op.f('ix_visual_pipelines_tenant_id'), 'visual_pipelines', ['tenant_id'], unique=False)
    op.create_table('executable_pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visual_pipeline_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('compiled_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('compiled_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['compiled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['visual_pipeline_id'], ['visual_pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executable_pipelines_tenant_id'), 'executable_pipelines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_executable_pipelines_visual_pipeline_id'), 'executable_pipelines', ['visual_pipeline_id'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('executable_pipeline_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipelinejobstatus'), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['executable_pipeline_id'], ['executable_pipelines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_jobs_executable_pipeline_id'), 'pipeline_jobs', ['executable_pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_tenant_id'), 'pipeline_jobs', ['tenant_id'], unique=False)
    op.drop_constraint('chats_tenant_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint('org_memberships_user_id_fkey', 'org_memberships', type_='foreignkey')
    op.drop_constraint('org_memberships_org_unit_id_fkey', 'org_memberships', type_='foreignkey')
    op.drop_constraint('org_memberships_tenant_id_fkey', 'org_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'org_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'org_memberships', 'org_units', ['org_unit_id'], ['id'])
    op.create_foreign_key(None, 'org_memberships', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('org_units_parent_id_fkey', 'org_units', type_='foreignkey')
    op.drop_constraint('org_units_tenant_id_fkey', 'org_units', type_='foreignkey')
    op.create_foreign_key(None, 'org_units', 'org_units', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'org_units', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('role_assignments_user_id_fkey', 'role_assignments', type_='foreignkey')
    op.drop_constraint('role_assignments_role_id_fkey', 'role_assignments', type_='foreignkey')
    op.drop_constraint('role_assignments_tenant_id_fkey', 'role_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'role_assignments', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_assignments', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'role_assignments', 'users', ['user_id'], ['id'])
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.drop_constraint('roles_tenant_id_fkey', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('tool_registry_tenant_id_fkey', 'tool_registry', type_='foreignkey')
    op.create_foreign_key(None, 'tool_registry', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('tool_versions_tool_id_fkey', 'tool_versions', type_='foreignkey')
    op.drop_constraint('tool_versions_created_by_fkey', 'tool_versions', type_='foreignkey')
    op.create_foreign_key(None, 'tool_versions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tool_versions', 'tool_registry', ['tool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_versions', type_='foreignkey')
    op.drop_constraint(None, 'tool_versions', type_='foreignkey')
    op.create_foreign_key('tool_versions_created_by_fkey', 'tool_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tool_versions_tool_id_fkey', 'tool_versions', 'tool_registry', ['tool_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tool_registry', type_='foreignkey')
    op.create_foreign_key('tool_registry_tenant_id_fkey', 'tool_registry', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key('roles_tenant_id_fkey', 'roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_assignments', type_='foreignkey')
    op.drop_constraint(None, 'role_assignments', type_='foreignkey')
    op.drop_constraint(None, 'role_assignments', type_='foreignkey')
    op.create_foreign_key('role_assignments_tenant_id_fkey', 'role_assignments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_assignments_role_id_fkey', 'role_assignments', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_assignments_user_id_fkey', 'role_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'org_units', type_='foreignkey')
    op.drop_constraint(None, 'org_units', type_='foreignkey')
    op.create_foreign_key('org_units_tenant_id_fkey', 'org_units', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('org_units_parent_id_fkey', 'org_units', 'org_units', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'org_memberships', type_='foreignkey')
    op.drop_constraint(None, 'org_memberships', type_='foreignkey')
    op.drop_constraint(None, 'org_memberships', type_='foreignkey')
    op.create_foreign_key('org_memberships_tenant_id_fkey', 'org_memberships', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('org_memberships_org_unit_id_fkey', 'org_memberships', 'org_units', ['org_unit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('org_memberships_user_id_fkey', 'org_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chats_tenant_id_fkey', 'chats', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pipeline_jobs_tenant_id'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_executable_pipeline_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_executable_pipelines_visual_pipeline_id'), table_name='executable_pipelines')
    op.drop_index(op.f('ix_executable_pipelines_tenant_id'), table_name='executable_pipelines')
    op.drop_table('executable_pipelines')
    op.drop_index(op.f('ix_visual_pipelines_tenant_id'), table_name='visual_pipelines')
    op.drop_index(op.f('ix_visual_pipelines_org_unit_id'), table_name='visual_pipelines')
    op.drop_table('visual_pipelines')
    # ### end Alembic commands ###
