"""add cascade delete to org_memberships_user_id_fkey

Revision ID: 57f3b4a27d0e
Revises: 9f127c4a1c42
Create Date: 2026-01-18 22:29:38.842110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f3b4a27d0e'
down_revision: Union[str, None] = '9f127c4a1c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('org_memberships_user_id_fkey', 'org_memberships', type_='foreignkey')
    op.create_foreign_key('org_memberships_user_id_fkey', 'org_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('org_memberships_user_id_fkey', 'org_memberships', type_='foreignkey')
    op.create_foreign_key('org_memberships_user_id_fkey', 'org_memberships', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
