"""update_operator_category_enum

Revision ID: 9f127c4a1c42
Revises: 3d15462ab421
Create Date: 2026-01-18 22:14:25.600646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f127c4a1c42'
down_revision: Union[str, None] = '3d15462ab421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
