"""remove_legacy_model_registry_fields

Revision ID: b6484bf3357d
Revises: 577de8d73b46
Create Date: 2026-01-19 21:36:23.555579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6484bf3357d'
down_revision: Union[str, None] = '577de8d73b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_registry', 'provider')
    op.drop_column('model_registry', 'max_tokens')
    op.drop_column('model_registry', 'cost_per_1k_output')
    op.drop_column('model_registry', 'context_window')
    op.drop_column('model_registry', 'cost_per_1k_input')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('cost_per_1k_input', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('model_registry', sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('model_registry', sa.Column('cost_per_1k_output', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('model_registry', sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('model_registry', sa.Column('provider', postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'AZURE', 'CUSTOM', 'GEMINI', 'HUGGINGFACE', 'LOCAL', 'COHERE', 'GROQ', 'MISTRAL', 'TOGETHER', name='modelprovidertype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
