"""Add ProviderConfig table

Revision ID: cdfb1a48b29a
Revises: 2f4d7ccd1f19
Create Date: 2026-01-31 19:42:47.774397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdfb1a48b29a'
down_revision: Union[str, None] = '2f4d7ccd1f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    # Use existing enum type
    sa.Column('provider', postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'AZURE', 'GEMINI', 'HUGGINGFACE', 'LOCAL', 'COHERE', 'GROQ', 'MISTRAL', 'TOGETHER', 'CUSTOM', name='modelprovidertype', create_type=False), nullable=False),
    sa.Column('provider_variant', sa.String(), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_configs_tenant_id'), 'provider_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_configs_tenant_id'), table_name='provider_configs')
    op.drop_table('provider_configs')
    # ### end Alembic commands ###
