from __future__ import annotations

from app.services.platform_native.agents import (
    agents_create,
    agents_create_shell,
    agents_execute,
    agents_get,
    agents_get_run,
    agents_graph_add_tool,
    agents_graph_apply_patch,
    agents_graph_get,
    agents_graph_remove_tool,
    agents_graph_set_instructions,
    agents_graph_set_model,
    agents_graph_validate_patch,
    agents_list,
    agents_nodes_catalog,
    agents_nodes_schema,
    agents_nodes_validate,
    agents_publish,
    agents_update,
    agents_validate,
)
from app.services.platform_native.assets import (
    artifacts_convert_kind,
    artifacts_create,
    artifacts_create_test_run,
    artifacts_delete,
    artifacts_get,
    artifacts_list,
    artifacts_publish,
    artifacts_update,
    credentials_create_or_update,
    credentials_list,
    knowledge_stores_create,
    knowledge_stores_create_or_update,
    knowledge_stores_list,
    knowledge_stores_update,
    models_create_or_update,
    models_list,
    prompts_list,
    tools_create,
    tools_create_or_update,
    tools_get,
    tools_list,
    tools_publish,
    tools_update,
)
from app.services.platform_native.governance import (
    orchestration_cancel_subtree,
    orchestration_evaluate_and_replan,
    orchestration_join,
    orchestration_query_tree,
)
from app.services.platform_native.rag import (
    rag_compile_visual_pipeline,
    rag_create_job,
    rag_create_pipeline_shell,
    rag_create_visual_pipeline,
    rag_get_executable_input_schema,
    rag_get_executable_pipeline,
    rag_get_job,
    rag_graph_apply_patch,
    rag_graph_attach_knowledge_store,
    rag_graph_get,
    rag_graph_set_pipeline_node_config,
    rag_graph_validate_patch,
    rag_list_visual_pipelines,
    rag_operators_catalog,
    rag_operators_schema,
    rag_update_visual_pipeline,
)


ACTION_HANDLERS = {
    "rag.list_visual_pipelines": rag_list_visual_pipelines,
    "rag.operators.catalog": rag_operators_catalog,
    "rag.operators.schema": rag_operators_schema,
    "rag.create_pipeline_shell": rag_create_pipeline_shell,
    "rag.create_visual_pipeline": rag_create_visual_pipeline,
    "rag.update_visual_pipeline": rag_update_visual_pipeline,
    "rag.graph.get": rag_graph_get,
    "rag.graph.validate_patch": rag_graph_validate_patch,
    "rag.graph.apply_patch": rag_graph_apply_patch,
    "rag.graph.attach_knowledge_store_to_node": rag_graph_attach_knowledge_store,
    "rag.graph.set_pipeline_node_config": rag_graph_set_pipeline_node_config,
    "rag.compile_visual_pipeline": rag_compile_visual_pipeline,
    "rag.get_executable_pipeline": rag_get_executable_pipeline,
    "rag.get_executable_input_schema": rag_get_executable_input_schema,
    "rag.create_job": rag_create_job,
    "rag.get_job": rag_get_job,
    "agents.list": agents_list,
    "agents.get": agents_get,
    "agents.create_shell": agents_create_shell,
    "agents.create": agents_create,
    "agents.update": agents_update,
    "agents.graph.get": agents_graph_get,
    "agents.graph.validate_patch": agents_graph_validate_patch,
    "agents.graph.apply_patch": agents_graph_apply_patch,
    "agents.graph.add_tool_to_agent_node": agents_graph_add_tool,
    "agents.graph.remove_tool_from_agent_node": agents_graph_remove_tool,
    "agents.graph.set_agent_model": agents_graph_set_model,
    "agents.graph.set_agent_instructions": agents_graph_set_instructions,
    "agents.publish": agents_publish,
    "agents.validate": agents_validate,
    "agents.nodes.catalog": agents_nodes_catalog,
    "agents.nodes.schema": agents_nodes_schema,
    "agents.nodes.validate": agents_nodes_validate,
    "agents.execute": agents_execute,
    "agents.start_run": agents_execute,
    "agents.get_run": agents_get_run,
    "tools.list": tools_list,
    "tools.get": tools_get,
    "tools.create": tools_create,
    "tools.update": tools_update,
    "tools.create_or_update": tools_create_or_update,
    "tools.publish": tools_publish,
    "artifacts.list": artifacts_list,
    "artifacts.get": artifacts_get,
    "artifacts.create": artifacts_create,
    "artifacts.update": artifacts_update,
    "artifacts.convert_kind": artifacts_convert_kind,
    "artifacts.create_test_run": artifacts_create_test_run,
    "artifacts.publish": artifacts_publish,
    "artifacts.delete": artifacts_delete,
    "models.list": models_list,
    "models.create_or_update": models_create_or_update,
    "prompts.list": prompts_list,
    "credentials.list": credentials_list,
    "credentials.create_or_update": credentials_create_or_update,
    "knowledge_stores.list": knowledge_stores_list,
    "knowledge_stores.create": knowledge_stores_create,
    "knowledge_stores.update": knowledge_stores_update,
    "knowledge_stores.create_or_update": knowledge_stores_create_or_update,
    "orchestration.join": orchestration_join,
    "orchestration.cancel_subtree": orchestration_cancel_subtree,
    "orchestration.evaluate_and_replan": orchestration_evaluate_and_replan,
    "orchestration.query_tree": orchestration_query_tree,
}
